name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          docker build -t tmdb-api-test .

      - name: Run tests with Docker
        run: |
          docker run --rm tmdb-api-test
