name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          docker build -t tmdb-api-test .

      - name: Run tests with Docker
        run: |
          docker run --rm  \
            -v ${{ github.workspace }}/test-reports:/app/reports \
            -e TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} \
            tmdb-api-test

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-reports/
          retention-days: 7
